spring:
  cassandra:
    contact-points: localhost  # Change if using a remote server
    port: 9042
    keyspace-name: keyspace1
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra
    schema-action: create_if_not_exists